//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodPlan
    {
        public int FoodItemID { get; set; }
        public int MealPlanID { get; set; }
        public int ID { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual MealPlan MealPlan { get; set; }
    }
}
