//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable04.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IBEEHEALTHEntities1 : DbContext
    {
        public IBEEHEALTHEntities1()
            : base("name=IBEEHEALTHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CityStore> CityStore { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<DietRecipe> DietRecipe { get; set; }
        public virtual DbSet<FoodCategory> FoodCategory { get; set; }
        public virtual DbSet<FoodDiet> FoodDiet { get; set; }
        public virtual DbSet<FoodItem> FoodItem { get; set; }
        public virtual DbSet<FoodPlan> FoodPlan { get; set; }
        public virtual DbSet<FoodRecipe> FoodRecipe { get; set; }
        public virtual DbSet<MealPlan> MealPlan { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
    }
}
